name: Publish Only

on:
  workflow_dispatch:

jobs:
  deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # install wasm-tools for sqlite
    - name: install wasm-tools
      run: dotnet workload install wasm-tools
      
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish Nonton/Nonton.csproj -c Release -o release --nologo
    
    - name: Commit wwwroot to published branch
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: published
        FOLDER: release/wwwroot
